gpio export 1 out
gpio export 2 out
gpio export 3 out
gpio export 4 out
gpio export 5 out
gpio export 6 out
gpio export 7 out
gpio export 8 out
gpio export 9 out
gpio export 10 out
gpio export 11 out
gpio export 12 out
gpio export 13 out
gpio export 14 out
gpio export 15 out
gpio export 16 out
gpio export 17 out
gpio export 18 out
gpio export 19 out
gpio export 20 out
gpio export 21 out
gpio export 22 out
